/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Token = IDL.Text;
export const UserProfile = IDL.Record({
  'premium' : IDL.Bool,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const CheckIn = IDL.Record({
  'emoji' : IDL.Text,
  'author' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteToken' : IDL.Func([], [Token], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInHistory' : IDL.Func([IDL.Nat], [IDL.Vec(CheckIn)], ['query']),
  'getPartner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getTodayCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWithToken' : IDL.Func([Token], [IDL.Principal], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPremiumStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'submitCheckIn' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Token = IDL.Text;
  const UserProfile = IDL.Record({ 'premium' : IDL.Bool, 'name' : IDL.Text });
  const Time = IDL.Int;
  const CheckIn = IDL.Record({
    'emoji' : IDL.Text,
    'author' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteToken' : IDL.Func([], [Token], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInHistory' : IDL.Func([IDL.Nat], [IDL.Vec(CheckIn)], ['query']),
    'getPartner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getTodayCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWithToken' : IDL.Func([Token], [IDL.Principal], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPremiumStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'submitCheckIn' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };