/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckIn {
  'emoji' : string,
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export type Token = string;
export interface UserProfile { 'premium' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteToken' : ActorMethod<[], Token>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInHistory' : ActorMethod<[bigint], Array<CheckIn>>,
  'getPartner' : ActorMethod<[], [] | [Principal]>,
  'getTodayCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPremium' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinWithToken' : ActorMethod<[Token], Principal>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPremiumStatus' : ActorMethod<[Principal, boolean], undefined>,
  'submitCheckIn' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];